#!/usr/bin/env bash
#
# One entry point for local dev: brings up Postgres+MinIO, installs deps,
# runs migrations/seed, and either starts both dev servers ("up", default)
# or runs the full test suite ("test") — same steps CI runs, just local.
#
# Usage:
#   ./scripts/dev.sh          # start Postgres+MinIO, migrate, seed, run API+web
#   ./scripts/dev.sh up       # same as above
#   ./scripts/dev.sh test     # migrate against a clean DB, run unit+e2e+lint+build
#   ./scripts/dev.sh seed     # (re)run the seed script only
#   ./scripts/dev.sh down     # stop Postgres+MinIO

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ACTION="${1:-up}"

check_docker() {
  if ! docker info >/dev/null 2>&1; then
    echo "Docker isn't accessible from this shell."
    echo "If you were just added to the docker group, log out/in (or run: newgrp docker) and try again."
    echo "Otherwise make sure Docker is installed and running."
    exit 1
  fi
}

ensure_env() {
  if [ ! -f apps/api/.env ]; then
    echo "Creating apps/api/.env from apps/api/.env.example (local dev defaults)."
    cp apps/api/.env.example apps/api/.env
  fi
  if [ ! -f apps/web/.env ]; then
    if use_emulator; then
      echo "Creating apps/web/.env for the local Auth emulator."
      cat > apps/web/.env <<'EOF'
# Auto-generated by scripts/dev.sh for local emulator dev.
# For real Firebase: put your web app's config here and delete
# the VITE_FIREBASE_AUTH_EMULATOR_HOST line.
VITE_FIREBASE_API_KEY="demo-api-key"
VITE_FIREBASE_AUTH_DOMAIN="hrms-platform-dev.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID="hrms-platform-dev"
VITE_FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
EOF
    else
      echo "Creating apps/web/.env from apps/web/.env.example — FILL IN the VITE_FIREBASE_* values."
      cp apps/web/.env.example apps/web/.env
    fi
  fi
}

# Real Firebase mode: verify the config that actually breaks things if absent
# (backend service account for token verification; web API key / auth domain,
# without which the web app renders a blank page). Prints exactly what's missing.
check_real_firebase_config() {
  use_emulator && return 0
  local missing=()
  grep -qE '^[[:space:]]*FIREBASE_SERVICE_ACCOUNT_JSON=[^[:space:]#]' apps/api/.env 2>/dev/null \
    || missing+=("apps/api/.env : FIREBASE_SERVICE_ACCOUNT_JSON  (service-account JSON on one line)")
  grep -qE '^[[:space:]]*VITE_FIREBASE_API_KEY="[^"]' apps/web/.env 2>/dev/null \
    || missing+=("apps/web/.env : VITE_FIREBASE_API_KEY")
  grep -qE '^[[:space:]]*VITE_FIREBASE_AUTH_DOMAIN="[^"]' apps/web/.env 2>/dev/null \
    || missing+=("apps/web/.env : VITE_FIREBASE_AUTH_DOMAIN  (<project-id>.firebaseapp.com)")
  [ ${#missing[@]} -eq 0 ] && return 0
  echo ""
  echo "Real Firebase mode (no FIREBASE_AUTH_EMULATOR_HOST in apps/api/.env), but:"
  printf '  missing  %s\n' "${missing[@]}"
  echo ""
  echo "Get these from the Firebase console: Project settings > General (web app"
  echo "config) and Project settings > Service accounts (Generate new private key)."
  echo "Or use the local emulator instead: add this line to apps/api/.env"
  echo "  FIREBASE_AUTH_EMULATOR_HOST=localhost:9099"
  exit 1
}

wait_for_postgres() {
  echo "Waiting for Postgres to be ready..."
  for _ in $(seq 1 30); do
    if docker compose exec -T postgres pg_isready -U hrms_superuser -d hrms >/dev/null 2>&1; then
      echo "Postgres is ready."
      return 0
    fi
    sleep 1
  done
  echo "Postgres didn't become ready in time. Check: docker compose logs postgres"
  exit 1
}

# Auth backend follows apps/api/.env: an uncommented FIREBASE_AUTH_EMULATOR_HOST
# means "use the local Auth emulator"; remove/comment it (and set real
# FIREBASE_PROJECT_ID + FIREBASE_SERVICE_ACCOUNT_JSON) to use real Firebase.
use_emulator() {
  grep -qE '^FIREBASE_AUTH_EMULATOR_HOST=' apps/api/.env 2>/dev/null
}

# Starts the local Firebase Auth emulator on :9099 (background, needs a JRE),
# but only when .env asks for it. Killed on exit via the trap below.
FIREBASE_EMULATOR_PID=""
start_firebase_emulator() {
  if ! use_emulator; then
    echo "Real Firebase mode (no FIREBASE_AUTH_EMULATOR_HOST in apps/api/.env) — not starting the local emulator."
    return 0
  fi
  if curl -sf -o /dev/null "http://127.0.0.1:9099" 2>/dev/null; then
    echo "Firebase Auth emulator already running on :9099."
    return 0
  fi
  echo "Starting Firebase Auth emulator (:9099)..."
  npx --yes firebase-tools emulators:start --only auth \
    --project "${FIREBASE_PROJECT_ID:-hrms-platform-dev}" \
    >/tmp/hrms-firebase-emulator.log 2>&1 &
  FIREBASE_EMULATOR_PID=$!
  for _ in $(seq 1 90); do
    if curl -sf -o /dev/null "http://127.0.0.1:9099" 2>/dev/null; then
      echo "Firebase Auth emulator is ready."
      return 0
    fi
    sleep 1
  done
  echo "Firebase Auth emulator didn't come up on :9099 — seed/e2e will fail."
  echo "Is Java installed? Log: /tmp/hrms-firebase-emulator.log"
}

trap '[ -n "${FIREBASE_EMULATOR_PID:-}" ] && kill "${FIREBASE_EMULATOR_PID}" 2>/dev/null; true' EXIT

case "$ACTION" in
  up)
    check_docker
    ensure_env
    check_real_firebase_config
    docker compose up -d
    wait_for_postgres
    npm run install:all
    npm run prisma:generate
    npm run prisma:migrate
    start_firebase_emulator
    if use_emulator; then
      npm run prisma:seed || echo "Seed skipped (likely already seeded — safe to ignore)."
    else
      echo "Real Firebase mode — skipping auto-seed. Run 'npm run prisma:seed' manually"
      echo "to create the demo tenants in your Firebase project."
    fi
    echo ""
    echo "Starting API (http://localhost:3000/api) and web (http://localhost:5173)."
    echo "Ctrl+C stops both."
    trap 'kill 0' EXIT
    npm run dev:api &
    npm run dev:web &
    wait
    ;;

  test)
    check_docker
    ensure_env
    check_real_firebase_config
    docker compose up -d
    wait_for_postgres
    npm run install:all
    npm run prisma:generate
    npm run prisma:migrate
    if ! use_emulator; then
      echo "ERROR: the e2e suite needs the Firebase Auth emulator to mint test ID tokens."
      echo "Set FIREBASE_AUTH_EMULATOR_HOST=localhost:9099 in apps/api/.env and retry."
      exit 1
    fi
    start_firebase_emulator
    echo ""
    echo "==> Backend unit tests"
    npm run test:api
    echo ""
    echo "==> Backend e2e tests (tenant isolation + auth, against real Postgres)"
    npm run test:api:e2e
    echo ""
    echo "==> Lint + build (api + web)"
    npm run lint
    npm run build
    echo ""
    echo "All checks passed."
    ;;

  seed)
    ensure_env
    check_real_firebase_config
    start_firebase_emulator
    npm run prisma:seed
    ;;

  down)
    docker compose down
    ;;

  *)
    echo "Usage: $0 [up|test|seed|down]"
    exit 1
    ;;
esac
